package com.qlchtl.views;

import java.awt.Component;
import javax.swing.*;

import com.qlchtl.dao.KhachHangDao;
import com.qlchtl.dao.KhoDao;
import com.qlchtl.dao.NhanVienDao;
import com.qlchtl.dao.SanPhamDao;
import com.qlchtl.entity.KhachHang;
import com.qlchtl.entity.Kho;
import com.qlchtl.entity.NhanVien;
import com.qlchtl.entity.SanPham;
import com.qlchtl.utils.MsgBox;
import com.qlchtl.views.MyControls.MyPanelBoxShadow;
import com.qlchtl.views.MyControls.MyScrollBar;
import com.qlchtl.views.MyControls.MyPanel;
import com.qlchtl.views.SubComponent.ClientForm;
import com.qlchtl.views.SubComponent.InvoiceForm;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

import javax.swing.JFrame;
import com.qlchtl.views.SubComponent.ItemProduct;
import com.qlchtl.views.SubComponent.ItemStaff;
import com.qlchtl.views.SubComponent.RankForm;

import java.util.List;


public class FormMain extends javax.swing.JFrame implements UpdateCallback{

    private LogIn lgin;
    private String idProductSelected;
    private String idStaffSelected;

    private String TYPE_SEARCHING = "PRODUCT";


    SanPhamDao sanPhamDao = new SanPhamDao();
    KhoDao khoDAo = new KhoDao();

    NhanVienDao nhanVienDao = new NhanVienDao();
    KhachHangDao khachHangDao = new KhachHangDao();

    public static String maSp;
    
    public String getIdProductSelected(){
        return this.idProductSelected;
    }
    public void setIdProductSelected(String a) {
        this.idProductSelected = a;
    }
    
    public String getIdStaffSelected(){
        return this.idStaffSelected;
    }
    public void setIdStaffSelected(String a) {
        this.idStaffSelected = a;
    }

    public FormMain(LogIn lgin) {
        initComponents();
        this.pnlProduct.setBackground(new Color(24,145,143));
        this.lblProduct.setForeground(Color.white);
        this.lgin = lgin;
        setLocationRelativeTo(null);
        settingScrollPane();
        setTupTabbedPane();
        loadSP();
    }

    private ClientForm clientForm = new ClientForm(this);
    private InvoiceForm invoiceForm = new InvoiceForm(this);
    private  RankForm rankForm = new RankForm(this);
    private void setTupTabbedPane() {
        
        tpnMain.addTab("", clientForm);
        tpnMain.addTab("", invoiceForm);
        tpnMain.addTab("", rankForm);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        myPanelBoxShadow1 = new com.qlchtl.views.MyControls.MyPanelBoxShadow();
        jLabel2 = new javax.swing.JLabel();
        pnlMenu = new javax.swing.JPanel();
        pnlProduct = new javax.swing.JPanel();
        lblProduct = new javax.swing.JLabel();
        pnlStaff = new javax.swing.JPanel();
        lblStaff = new javax.swing.JLabel();
        pnlClient = new javax.swing.JPanel();
        lblClient = new javax.swing.JLabel();
        pnlInvoice = new javax.swing.JPanel();
        lblInvoice = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblRank = new javax.swing.JLabel();
        pnlShift = new javax.swing.JPanel();
        lblShift = new javax.swing.JLabel();
        pnlAccount = new javax.swing.JPanel();
        lblAccount = new javax.swing.JLabel();
        iconProduct = new javax.swing.JLabel();
        iconStaff = new javax.swing.JLabel();
        iconClient = new javax.swing.JLabel();
        iconInvoice = new javax.swing.JLabel();
        iconRank = new javax.swing.JLabel();
        iconShift = new javax.swing.JLabel();
        iconAccount = new javax.swing.JLabel();
        myPanelBoxShadow3 = new com.qlchtl.views.MyControls.MyPanelBoxShadow();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        myPanel1 = new com.qlchtl.views.MyControls.MyPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        lblGoSearch = new javax.swing.JLabel();
        pnlHome = new com.qlchtl.views.MyControls.MyPanelBoxShadow();
        lblHome = new javax.swing.JLabel();
        lblTabName = new javax.swing.JLabel();
        lblLogout = new javax.swing.JLabel();
        tpnMain = new javax.swing.JTabbedPane();
        ucProduct = new javax.swing.JPanel();
        myPanelBoxShadow4 = new com.qlchtl.views.MyControls.MyPanelBoxShadow();
        imgProductFound = new javax.swing.JLabel();
        lblProductNameFound = new javax.swing.JLabel();
        btnViewProductFound = new com.qlchtl.views.MyControls.MyButton();
        jLabel12 = new javax.swing.JLabel();
        lblCodeProductFound = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblPriceProdFound = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lblQuantityProductFound = new javax.swing.JLabel();
        btnDeleteProdFound = new com.qlchtl.views.MyControls.MyButton();
        scpProduct = new javax.swing.JScrollPane();
        myPanel2 = new com.qlchtl.views.MyControls.MyPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        myPanel3 = new com.qlchtl.views.MyControls.MyPanel();
        jLabel18 = new javax.swing.JLabel();
        pnlAddNewPrd = new com.qlchtl.views.MyControls.MyPanelBoxShadow();
        lblAddNewProd = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        ucStaff = new javax.swing.JPanel();
        pnlScrollStaff = new javax.swing.JPanel();
        pnlHeaderStaff = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        btnAddStaff = new com.qlchtl.views.MyControls.MyButton();
        scpStaff = new javax.swing.JScrollPane();
        myPanelBoxShadow2 = new com.qlchtl.views.MyControls.MyPanelBoxShadow();
        lblNameStaffFound = new javax.swing.JLabel();
        lblCodeStaffFound = new javax.swing.JLabel();
        lblStateStaffFound = new javax.swing.JLabel();
        lblPhoneStaffFound = new javax.swing.JLabel();
        btnDetailStaffFound = new com.qlchtl.views.MyControls.MyButton();
        btnDeleteStaffFound = new com.qlchtl.views.MyControls.MyButton();
        lblAvataStaffFound = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        pnlMain.setBackground(new java.awt.Color(250, 250, 250));
        pnlMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myPanelBoxShadow1.setBackground(new java.awt.Color(255, 255, 255));
        myPanelBoxShadow1.setShadowOpacity(0.3F);
        myPanelBoxShadow1.setShadowSize(5);
        myPanelBoxShadow1.setVerifyInputWhenFocusTarget(false);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/letter-k.png"))); // NOI18N

        pnlMenu.setBackground(new java.awt.Color(255, 255, 255));

        pnlProduct.setBackground(new java.awt.Color(255, 255, 255));
        pnlProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProductClick(evt);
            }
        });

        lblProduct.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblProduct.setForeground(new java.awt.Color(102, 102, 102));
        lblProduct.setText("Product");
        lblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ProductClick(evt);
            }
        });

        javax.swing.GroupLayout pnlProductLayout = new javax.swing.GroupLayout(pnlProduct);
        pnlProduct.setLayout(pnlProductLayout);
        pnlProductLayout.setHorizontalGroup(
            pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        pnlProductLayout.setVerticalGroup(
            pnlProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlProductLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        pnlStaff.setBackground(new java.awt.Color(255, 255, 255));
        pnlStaff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlStaff.setPreferredSize(new java.awt.Dimension(211, 54));
        pnlStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffclick(evt);
            }
        });

        lblStaff.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblStaff.setForeground(new java.awt.Color(102, 102, 102));
        lblStaff.setText("Staff");
        lblStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffclick(evt);
            }
        });

        javax.swing.GroupLayout pnlStaffLayout = new javax.swing.GroupLayout(pnlStaff);
        pnlStaff.setLayout(pnlStaffLayout);
        pnlStaffLayout.setHorizontalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );
        pnlStaffLayout.setVerticalGroup(
            pnlStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStaffLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );

        pnlClient.setBackground(new java.awt.Color(255, 255, 255));
        pnlClient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlClient.setPreferredSize(new java.awt.Dimension(211, 54));
        pnlClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClientClick(evt);
            }
        });

        lblClient.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblClient.setForeground(new java.awt.Color(102, 102, 102));
        lblClient.setText("Client");
        lblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ClientClick(evt);
            }
        });

        javax.swing.GroupLayout pnlClientLayout = new javax.swing.GroupLayout(pnlClient);
        pnlClient.setLayout(pnlClientLayout);
        pnlClientLayout.setHorizontalGroup(
            pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblClient, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlClientLayout.setVerticalGroup(
            pnlClientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlClientLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblClient, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pnlInvoice.setBackground(new java.awt.Color(255, 255, 255));
        pnlInvoice.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlInvoice.setPreferredSize(new java.awt.Dimension(0, 54));
        pnlInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InvoiceClick(evt);
            }
        });

        lblInvoice.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblInvoice.setForeground(new java.awt.Color(102, 102, 102));
        lblInvoice.setText("Invoice");
        lblInvoice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InvoiceClick(evt);
            }
        });

        javax.swing.GroupLayout pnlInvoiceLayout = new javax.swing.GroupLayout(pnlInvoice);
        pnlInvoice.setLayout(pnlInvoiceLayout);
        pnlInvoiceLayout.setHorizontalGroup(
            pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(43, 43, 43))
        );
        pnlInvoiceLayout.setVerticalGroup(
            pnlInvoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoiceLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RankClick(evt);
            }
        });

        lblRank.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblRank.setForeground(new java.awt.Color(102, 102, 102));
        lblRank.setText("Rank");
        lblRank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RankClick(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblRank, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblRank, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        pnlShift.setBackground(new java.awt.Color(255, 255, 255));
        pnlShift.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlShift.setPreferredSize(new java.awt.Dimension(0, 54));
        pnlShift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShiftClick(evt);
            }
        });

        lblShift.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblShift.setForeground(new java.awt.Color(102, 102, 102));
        lblShift.setText("Shift");
        lblShift.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ShiftClick(evt);
            }
        });

        javax.swing.GroupLayout pnlShiftLayout = new javax.swing.GroupLayout(pnlShift);
        pnlShift.setLayout(pnlShiftLayout);
        pnlShiftLayout.setHorizontalGroup(
            pnlShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShiftLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblShift, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlShiftLayout.setVerticalGroup(
            pnlShiftLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShiftLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblShift, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pnlAccount.setBackground(new java.awt.Color(255, 255, 255));
        pnlAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlAccount.setPreferredSize(new java.awt.Dimension(0, 54));
        pnlAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AccountClick(evt);
            }
        });

        lblAccount.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblAccount.setForeground(new java.awt.Color(102, 102, 102));
        lblAccount.setText("Account");
        lblAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                menuItemLeave(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AccountClick(evt);
            }
        });

        javax.swing.GroupLayout pnlAccountLayout = new javax.swing.GroupLayout(pnlAccount);
        pnlAccount.setLayout(pnlAccountLayout);
        pnlAccountLayout.setHorizontalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAccount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAccountLayout.setVerticalGroup(
            pnlAccountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAccountLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        iconProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/home.png"))); // NOI18N

        iconStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/team.png"))); // NOI18N

        iconClient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/public-relation.png"))); // NOI18N

        iconInvoice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/bill.png"))); // NOI18N

        iconRank.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/badge.png"))); // NOI18N

        iconShift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/shift.png"))); // NOI18N

        iconAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/user.png"))); // NOI18N
        iconAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuItemHover(evt);
            }
        });

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconClient, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconInvoice, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(iconShift, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconAccount, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconRank, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)))
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlShift, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInvoice, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(pnlClient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(pnlStaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(pnlAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(pnlProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(pnlProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(iconProduct, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(17, 17, 17)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlClient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(iconInvoice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(iconRank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlShift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(iconShift, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(pnlAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(105, 105, 105))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addComponent(iconAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        myPanelBoxShadow3.setBackground(new java.awt.Color(255, 255, 255));
        myPanelBoxShadow3.setShadowColor(new java.awt.Color(10, 200, 186));
        myPanelBoxShadow3.setShadowOpacity(0.2F);

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 142, 168));
        jLabel1.setText("Xirkle K");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout myPanelBoxShadow3Layout = new javax.swing.GroupLayout(myPanelBoxShadow3);
        myPanelBoxShadow3.setLayout(myPanelBoxShadow3Layout);
        myPanelBoxShadow3Layout.setHorizontalGroup(
            myPanelBoxShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelBoxShadow3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(17, 17, 17))
        );
        myPanelBoxShadow3Layout.setVerticalGroup(
            myPanelBoxShadow3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelBoxShadow3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout myPanelBoxShadow1Layout = new javax.swing.GroupLayout(myPanelBoxShadow1);
        myPanelBoxShadow1.setLayout(myPanelBoxShadow1Layout);
        myPanelBoxShadow1Layout.setHorizontalGroup(
            myPanelBoxShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelBoxShadow1Layout.createSequentialGroup()
                .addGroup(myPanelBoxShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, myPanelBoxShadow1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(myPanelBoxShadow1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myPanelBoxShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        myPanelBoxShadow1Layout.setVerticalGroup(
            myPanelBoxShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelBoxShadow1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(myPanelBoxShadow1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                    .addGroup(myPanelBoxShadow1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(myPanelBoxShadow3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(99, 99, 99)
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pnlMain.add(myPanelBoxShadow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 240, 770));

        jPanel2.setBackground(new java.awt.Color(252, 252, 252));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myPanel1.setBackground(new java.awt.Color(255, 255, 255));
        myPanel1.setRoundBottomLeft(40);
        myPanel1.setRoundBottomRight(40);
        myPanel1.setRoundTopLeft(40);
        myPanel1.setRoundTopRight(40);
        myPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/search-interface-symbol.png"))); // NOI18N
        myPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 7, 37, -1));

        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(102, 102, 102));
        txtSearch.setBorder(null);
        myPanel1.add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 5, 200, 30));

        lblGoSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/enter.png"))); // NOI18N
        lblGoSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGoSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGoSearchMouseClicked(evt);
            }
        });
        myPanel1.add(lblGoSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 10, -1, -1));

        jPanel2.add(myPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 5, 300, 40));

        pnlHome.setBackground(new java.awt.Color(205, 247, 244));
        pnlHome.setShadowOpacity(0.2F);
        pnlHome.setShadowSize(2);
        pnlHome.setShadowType(com.qlchtl.views.MyControls.ShadowType.BOT);
        pnlHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeClick(evt);
            }
        });

        lblHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/user (1).png"))); // NOI18N
        lblHome.setPreferredSize(new java.awt.Dimension(30, 24));
        lblHome.setVerifyInputWhenFocusTarget(false);
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeClick(evt);
            }
        });

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(pnlHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 5, 35, 40));

        lblTabName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTabName.setForeground(new java.awt.Color(21, 123, 142));
        lblTabName.setText("Product");
        jPanel2.add(lblTabName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 180, 40));

        lblLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/logout.png"))); // NOI18N
        jPanel2.add(lblLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        pnlMain.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 910, 50));

        ucProduct.setBackground(new java.awt.Color(252, 252, 252));
        ucProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        myPanelBoxShadow4.setBackground(new java.awt.Color(255, 255, 255));
        myPanelBoxShadow4.setShadowOpacity(0.2F);
        myPanelBoxShadow4.setShadowSize(10);

        imgProductFound.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/headphone.png"))); // NOI18N
        imgProductFound.setText("jLabel4");

        lblProductNameFound.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        lblProductNameFound.setText("Head Phone VGR Version 12");

        btnViewProductFound.setForeground(new java.awt.Color(255, 255, 255));
        btnViewProductFound.setText("View Detail");
        btnViewProductFound.setBorderColor(new java.awt.Color(24, 145, 143));
        btnViewProductFound.setColor(new java.awt.Color(24, 145, 143));
        btnViewProductFound.setColorClick(new java.awt.Color(19, 120, 118));
        btnViewProductFound.setColorOver(new java.awt.Color(47, 173, 171));
        btnViewProductFound.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        btnViewProductFound.setRadius(15);
        btnViewProductFound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetailProdFoundClick(evt);
            }
        });
        btnViewProductFound.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProductFoundActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Code Product:");

        lblCodeProductFound.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCodeProductFound.setForeground(new java.awt.Color(102, 102, 102));
        lblCodeProductFound.setText("103122431");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(10, 200, 186));
        jLabel13.setText("Price:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(10, 200, 186));
        jLabel14.setText("$");

        lblPriceProdFound.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPriceProdFound.setForeground(new java.awt.Color(10, 200, 186));
        lblPriceProdFound.setText("12.000");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Quantity:");

        lblQuantityProductFound.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblQuantityProductFound.setForeground(new java.awt.Color(102, 102, 102));
        lblQuantityProductFound.setText("10");

        btnDeleteProdFound.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteProdFound.setText("Delete");
        btnDeleteProdFound.setBorderColor(new java.awt.Color(232, 113, 122));
        btnDeleteProdFound.setColor(new java.awt.Color(235, 40, 54));
        btnDeleteProdFound.setColorClick(new java.awt.Color(235, 40, 54));
        btnDeleteProdFound.setColorOver(new java.awt.Color(232, 113, 122));
        btnDeleteProdFound.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteProdFound.setRadius(15);
        btnDeleteProdFound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteProdFoundMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout myPanelBoxShadow4Layout = new javax.swing.GroupLayout(myPanelBoxShadow4);
        myPanelBoxShadow4.setLayout(myPanelBoxShadow4Layout);
        myPanelBoxShadow4Layout.setHorizontalGroup(
            myPanelBoxShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelBoxShadow4Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(imgProductFound, javax.swing.GroupLayout.PREFERRED_SIZE, 192, Short.MAX_VALUE)
                .addGroup(myPanelBoxShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanelBoxShadow4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(myPanelBoxShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProductNameFound, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addGroup(myPanelBoxShadow4Layout.createSequentialGroup()
                                .addGroup(myPanelBoxShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(myPanelBoxShadow4Layout.createSequentialGroup()
                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(22, 22, 22)
                                        .addComponent(lblCodeProductFound, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE))
                                    .addGroup(myPanelBoxShadow4Layout.createSequentialGroup()
                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(70, 70, 70)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(13, 13, 13)
                                        .addComponent(lblPriceProdFound, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE))
                                    .addGroup(myPanelBoxShadow4Layout.createSequentialGroup()
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(48, 48, 48)
                                        .addComponent(lblQuantityProductFound, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                                .addGap(10, 10, 10))))
                    .addGroup(myPanelBoxShadow4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDeleteProdFound, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(btnViewProductFound, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                        .addGap(20, 20, 20)))
                .addGap(21, 21, 21))
        );
        myPanelBoxShadow4Layout.setVerticalGroup(
            myPanelBoxShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanelBoxShadow4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(imgProductFound, javax.swing.GroupLayout.PREFERRED_SIZE, 180, Short.MAX_VALUE)
                .addGap(31, 31, 31))
            .addGroup(myPanelBoxShadow4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblProductNameFound, javax.swing.GroupLayout.PREFERRED_SIZE, 18, Short.MAX_VALUE)
                .addGap(17, 17, 17)
                .addGroup(myPanelBoxShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCodeProductFound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(myPanelBoxShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPriceProdFound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(myPanelBoxShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblQuantityProductFound, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(myPanelBoxShadow4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewProductFound, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnDeleteProdFound, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );

        ucProduct.add(myPanelBoxShadow4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 481, 231));

        scpProduct.setBackground(new java.awt.Color(255, 250, 245));
        scpProduct.setBorder(null);
        scpProduct.setHorizontalScrollBar(null);
        ucProduct.add(scpProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 890, 450));

        myPanel2.setBackground(new java.awt.Color(109, 216, 234));
        myPanel2.setRoundBottomLeft(15);
        myPanel2.setRoundBottomRight(15);
        myPanel2.setRoundTopLeft(15);
        myPanel2.setRoundTopRight(15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(21, 123, 142));
        jLabel4.setText("right here");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(21, 123, 142));
        jLabel17.setText("Work with the products");

        myPanel3.setBackground(new java.awt.Color(109, 216, 234));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Add a product");

        pnlAddNewPrd.setBackground(new java.awt.Color(10, 200, 186));
        pnlAddNewPrd.setShadowColor(new java.awt.Color(0, 110, 101));
        pnlAddNewPrd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewProductClick(evt);
            }
        });

        lblAddNewProd.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        lblAddNewProd.setForeground(new java.awt.Color(255, 255, 255));
        lblAddNewProd.setText("+");
        lblAddNewProd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAddNewProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddNewProductClick(evt);
            }
        });

        javax.swing.GroupLayout pnlAddNewPrdLayout = new javax.swing.GroupLayout(pnlAddNewPrd);
        pnlAddNewPrd.setLayout(pnlAddNewPrdLayout);
        pnlAddNewPrdLayout.setHorizontalGroup(
            pnlAddNewPrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNewPrdLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblAddNewProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        pnlAddNewPrdLayout.setVerticalGroup(
            pnlAddNewPrdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAddNewPrdLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddNewProd, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout myPanel3Layout = new javax.swing.GroupLayout(myPanel3);
        myPanel3.setLayout(myPanel3Layout);
        myPanel3Layout.setHorizontalGroup(
            myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAddNewPrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        myPanel3Layout.setVerticalGroup(
            myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                .addComponent(pnlAddNewPrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/qlchtl/image/action-r.png"))); // NOI18N
        jLabel20.setText("jLabel20");

        javax.swing.GroupLayout myPanel2Layout = new javax.swing.GroupLayout(myPanel2);
        myPanel2.setLayout(myPanel2Layout);
        myPanel2Layout.setHorizontalGroup(
            myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(128, 128, 128))
                    .addGroup(myPanel2Layout.createSequentialGroup()
                        .addGroup(myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(myPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        myPanel2Layout.setVerticalGroup(
            myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(myPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ucProduct.add(myPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 390, 210));

        tpnMain.addTab("tab1", ucProduct);

        ucStaff.setBackground(new java.awt.Color(255, 255, 255));

        pnlScrollStaff.setBackground(new java.awt.Color(255, 255, 255));
        pnlScrollStaff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0), 2));

        pnlHeaderStaff.setBackground(new java.awt.Color(255, 255, 255));
        pnlHeaderStaff.setFocusCycleRoot(true);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Name");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Code");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Phone Number");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("Gender");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(102, 102, 102));
        jLabel27.setText("Action");

        btnAddStaff.setForeground(new java.awt.Color(24, 145, 143));
        btnAddStaff.setText("Add Staff");
        btnAddStaff.setBorderColor(new java.awt.Color(24, 145, 143));
        btnAddStaff.setColorClick(new java.awt.Color(255, 255, 255));
        btnAddStaff.setColorOver(new java.awt.Color(204, 204, 204));
        btnAddStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddStaff.setRadius(50);

        javax.swing.GroupLayout pnlHeaderStaffLayout = new javax.swing.GroupLayout(pnlHeaderStaff);
        pnlHeaderStaff.setLayout(pnlHeaderStaffLayout);
        pnlHeaderStaffLayout.setHorizontalGroup(
            pnlHeaderStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(jLabel25)
                .addGap(55, 55, 55)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(85, 85, 85))
        );
        pnlHeaderStaffLayout.setVerticalGroup(
            pnlHeaderStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHeaderStaffLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(pnlHeaderStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26)
                    .addComponent(jLabel27)
                    .addComponent(btnAddStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scpStaff.setBorder(null);

        javax.swing.GroupLayout pnlScrollStaffLayout = new javax.swing.GroupLayout(pnlScrollStaff);
        pnlScrollStaff.setLayout(pnlScrollStaffLayout);
        pnlScrollStaffLayout.setHorizontalGroup(
            pnlScrollStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScrollStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlScrollStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlHeaderStaff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scpStaff))
                .addContainerGap())
        );
        pnlScrollStaffLayout.setVerticalGroup(
            pnlScrollStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlScrollStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHeaderStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpStaff, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                .addContainerGap())
        );

        myPanelBoxShadow2.setBackground(new java.awt.Color(255, 255, 255));
        myPanelBoxShadow2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNameStaffFound.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblNameStaffFound.setForeground(new java.awt.Color(51, 51, 51));
        lblNameStaffFound.setText("Phạm Hữu Tuấn");
        myPanelBoxShadow2.add(lblNameStaffFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 16, 218, -1));

        lblCodeStaffFound.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCodeStaffFound.setForeground(new java.awt.Color(102, 102, 102));
        lblCodeStaffFound.setText("21110713");
        myPanelBoxShadow2.add(lblCodeStaffFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 53, 206, -1));

        lblStateStaffFound.setBackground(new java.awt.Color(102, 102, 102));
        lblStateStaffFound.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblStateStaffFound.setForeground(new java.awt.Color(102, 102, 102));
        lblStateStaffFound.setText("Đang làm");
        myPanelBoxShadow2.add(lblStateStaffFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 75, 206, -1));

        lblPhoneStaffFound.setBackground(new java.awt.Color(102, 102, 102));
        lblPhoneStaffFound.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPhoneStaffFound.setForeground(new java.awt.Color(102, 102, 102));
        lblPhoneStaffFound.setText("0928895717");
        myPanelBoxShadow2.add(lblPhoneStaffFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 97, 206, -1));

        btnDetailStaffFound.setForeground(new java.awt.Color(255, 255, 255));
        btnDetailStaffFound.setText("Detail");
        btnDetailStaffFound.setBorderColor(new java.awt.Color(24, 145, 143));
        btnDetailStaffFound.setColor(new java.awt.Color(24, 145, 143));
        btnDetailStaffFound.setColorClick(new java.awt.Color(19, 120, 118));
        btnDetailStaffFound.setColorOver(new java.awt.Color(47, 173, 171));
        btnDetailStaffFound.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDetailStaffFound.setRadius(20);
        btnDetailStaffFound.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StaffFoundClick(evt);
            }
        });
        myPanelBoxShadow2.add(btnDetailStaffFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 125, 110, 46));

        btnDeleteStaffFound.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteStaffFound.setText("Delete");
        btnDeleteStaffFound.setBorderColor(new java.awt.Color(235, 40, 54));
        btnDeleteStaffFound.setColor(new java.awt.Color(235, 40, 54));
        btnDeleteStaffFound.setColorClick(new java.awt.Color(235, 40, 54));
        btnDeleteStaffFound.setColorOver(new java.awt.Color(232, 113, 122));
        btnDeleteStaffFound.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDeleteStaffFound.setRadius(20);
        myPanelBoxShadow2.add(btnDeleteStaffFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 125, 89, 46));
        myPanelBoxShadow2.add(lblAvataStaffFound, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 15, 140, 150));

        javax.swing.GroupLayout ucStaffLayout = new javax.swing.GroupLayout(ucStaff);
        ucStaff.setLayout(ucStaffLayout);
        ucStaffLayout.setHorizontalGroup(
            ucStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ucStaffLayout.createSequentialGroup()
                .addGroup(ucStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ucStaffLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(pnlScrollStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ucStaffLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(myPanelBoxShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ucStaffLayout.setVerticalGroup(
            ucStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ucStaffLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(myPanelBoxShadow2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlScrollStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        tpnMain.addTab("tab2", ucStaff);

        pnlMain.add(tpnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 910, 750));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlMain, javax.swing.GroupLayout.PREFERRED_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void settingScrollPane() {
        MyScrollBar scrbprod =  new MyScrollBar();
        scrbprod.setUnitIncrement(50);
        scrbprod.setBlockIncrement(50);
        scrbprod.setForeground(new Color(24,145,143));
        scpProduct.setVerticalScrollBar(scrbprod);
         MyScrollBar scrbstaff =  new MyScrollBar();
         scrbstaff.setUnitIncrement(30);
        scrbstaff.setBlockIncrement(30);
        scrbstaff.setForeground(new Color(24,145,143));
        scpStaff.setVerticalScrollBar(scrbstaff);
    }    


    private Runnable renderStaffItem(List<NhanVien> listnv) {
        Component viewport = scpStaff.getViewport().getView();
        if (viewport instanceof JPanel) {
            scpStaff.setViewportView(null);
        }
        JPanel pnl = new JPanel();
        pnl.setLayout(null);
        pnl.setBackground(Color.white);
        pnl.setPreferredSize(new Dimension(scpStaff.getPreferredSize().width, 0));
        ItemStaff itf = new ItemStaff(this);
        Runnable a = new Runnable() {
            @Override
            public void run() {
                int col = 0;
                int row = 0;
                for (NhanVien cd :listnv) {
                    MyPanelBoxShadow pn = itf.createItemStaffComponent(col, row, cd.getMaNV(), cd.getHoTenNV(), cd.getGioiTinh(), cd.isTrangThai(), cd.getSdt(), cd.getImg());
                    if (col == 0 && row == 0) {
                        idStaffSelected = cd.getMaNV();
                        setStaffFound(cd.getHoTenNV(), cd.isTrangThai(),cd.getMaNV(),cd.getSdt(), cd.getImg());
                    }
                    pnl.add((Component) pn);
                    col++; 
                    if (col >= 1) {
                        col = 0;
                        row++;
                        SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                int height = pnl.getPreferredSize().height + pn.getHeight() + 10;
                                pnl.setPreferredSize(new Dimension(scpStaff.getPreferredSize().width, height));
                            }
                        });
                    }

                }
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        scpStaff.setViewportView(pnl);
                    }
                });
            }
        };
        return a;
    }
    

    private Runnable renderProdItem(List<SanPham> listsp) {
        Component viewport = scpProduct.getViewport().getView();
        if (viewport instanceof JPanel) {
            scpProduct.setViewportView(null);
        }
        JPanel pnl = new JPanel();
        pnl.setLayout(null);
        pnl.setBackground(Color.white);

        pnl.setPreferredSize(new Dimension(scpProduct.getPreferredSize().width,0));
        ItemProduct itpd = new ItemProduct(this);

        Runnable a = new Runnable() {
            @Override
            public void run() {
                int col = 0;
                int row = 0;
                int size = 0;
                for (SanPham cd : listsp) {

                    if(!cd.getTrangThai().equals("0")) {
                        Kho kho = khoDAo.selectById(cd.getMaSP());
                        size++;
                        MyPanelBoxShadow pn = itpd.createItemProdComponent(col, row, cd.getMaSP(), cd.getTenSP(), cd.getImg(), cd.getTienGoc(), String.valueOf(kho.getSoLuong()));
                        if (col == 0 && row == 0) {
                            idProductSelected = cd.getMaSP();
                            setProductSelected(cd.getImg(), cd.getTenSP(), cd.getTienGoc(), String.valueOf(kho.getSoLuong()));
                        }
                        pnl.add((Component) pn);
                        col++;
                        if (col > 2) {
                            col = 0;
                            row++;

                        }
                        final int finalRow = row;
                        final int finalSize = size;
                        SwingUtilities.invokeLater(new Runnable() {
                            public void run() {
                                int height = 0;
                                if(finalSize%3==0){
                                     height = finalRow * pn.getHeight() + 10 * finalRow;
                                }
                                else {
                                     height = (finalRow +1 ) * pn.getHeight() + 10 * (finalRow +1);
                                }
                                pnl.setPreferredSize(new Dimension(scpProduct.getPreferredSize().width, height));
                            }
                        });
                    }
                }
                SwingUtilities.invokeLater(new Runnable() {
                    public void run() {
                        scpProduct.setViewportView(pnl);
                    }
                });
            }
        };
        return a;
    }

    
    public void setStaffFound(String name, Boolean state,String code, String phone, String img) {
        lblNameStaffFound.setText(name);
        lblCodeStaffFound.setText(code);
        String imagePath = "/com/qlchtl/image/imageSanPham/"+img;
        java.net.URL imageURL = getClass().getResource(imagePath);
        javax.swing.ImageIcon originalImageIcon = new javax.swing.ImageIcon(imageURL);
        java.awt.Image originalImage = originalImageIcon.getImage();
        java.awt.Image scaledImage = originalImage.getScaledInstance(140, 150, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledImageIcon = new javax.swing.ImageIcon(scaledImage);
        lblAvataStaffFound.setIcon(scaledImageIcon);


        if(state==true){
            lblStateStaffFound.setText("Đang làm");

        }
        else{
            lblStateStaffFound.setText("Nghỉ việc");
        }
        lblPhoneStaffFound.setText(phone);
    }



    public void setProductSelected(String urlImage,String name, String price, String quantity) {
        String imagePath = "/com/qlchtl/image/imageSanPham/"+urlImage;
        java.net.URL imageURL = getClass().getResource(imagePath);
        javax.swing.ImageIcon originalImageIcon = new javax.swing.ImageIcon(imageURL);
        java.awt.Image originalImage = originalImageIcon.getImage();
        java.awt.Image scaledImage = originalImage.getScaledInstance(200, 170, java.awt.Image.SCALE_SMOOTH);
        javax.swing.ImageIcon scaledImageIcon = new javax.swing.ImageIcon(scaledImage);
        imgProductFound.setIcon(scaledImageIcon);
        lblProductNameFound.setText(name);
        lblCodeProductFound.setText(idProductSelected);
        lblPriceProdFound.setText(price);

        if(!quantity.equals("0")){
            lblQuantityProductFound.setText("Còn Hàng");
        }
        else{
            lblQuantityProductFound.setText("Hết Hàng");

        }

    }
    
    private void renderItemStaffWithThread(List<NhanVien> listsp) {
        Thread a = new Thread(renderStaffItem(listsp));
        a.start();
    }
    
    private void renderItemProdWithThread( List<SanPham> listsp) {
        Thread a = new Thread(renderProdItem(listsp));
        a.start();
    }
    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseEntered

    private void menuItemHover(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemHover
        // TODO add your handling code here:
        Component hoveredComponent = evt.getComponent();
        JPanel res = null;
        if(hoveredComponent instanceof  JLabel){
            res = (JPanel)((JLabel) hoveredComponent).getParent();
        } else if(hoveredComponent instanceof JPanel){
            res = (JPanel) hoveredComponent;
        }
        if(res.getBackground().equals(Color.white)) {
             res.setBackground(new Color(228,236,230));
        }
    }//GEN-LAST:event_menuItemHover
 
    private void menuItemLeave(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuItemLeave
        // TODO add your handling code here:
        Component hoveredComponent = evt.getComponent();
        JPanel res = null;
        if(hoveredComponent instanceof  JLabel){
            res = (JPanel)((JLabel) hoveredComponent).getParent();
        } else if(hoveredComponent instanceof JPanel){
            res = (JPanel) hoveredComponent;
        }
        if(res.getBackground().equals(new Color(228,236,230))) {
            res.setBackground(Color.white);
            for (Component c : res.getComponents()) {
                if (c instanceof JLabel) {
                    c.setForeground(new Color(102, 102, 102));
                }
            }
        }else {
            setPresentTabVisible(evt,new Color(24,145,143),Color.white);
        }
    }//GEN-LAST:event_menuItemLeave

    private void staffclick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffclick
        // TODO add your handling code here:

        tpnMain.setSelectedIndex(1);   
        setPresentTabVisible(evt,new Color(24,145,143),Color.white);

        tpnMain.setSelectedIndex(1);  
        List<NhanVien> nhanVienList = nhanVienDao.selectAll();
        renderItemStaffWithThread(nhanVienList);
        this.TYPE_SEARCHING = "STAFF";
    }//GEN-LAST:event_staffclick


    private void ProductClick(java.awt.event.MouseEvent evt) {                              
                            
        // TODO add your handling code here:
        tpnMain.setSelectedIndex(0);  
        setPresentTabVisible(evt,new Color(24,145,143),Color.white);
        this.TYPE_SEARCHING = "PRODUCT";
    }                             

    
    private void ClientClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientClick
        // TODO add your handling code here:
         tpnMain.setSelectedIndex(2);
        setPresentTabVisible(evt,new Color(24,145,143),Color.white);
        this.TYPE_SEARCHING = "CLIENT";

    }//GEN-LAST:event_ClientClick

    private void InvoiceClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvoiceClick
        // TODO add your handling code here:
        tpnMain.setSelectedIndex(3);
        setPresentTabVisible(evt,new Color(24,145,143),Color.white);
        this.TYPE_SEARCHING = "INVOICE";

    }//GEN-LAST:event_InvoiceClick

    private void RankClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RankClick
        // TODO add your handling code here:
        tpnMain.setSelectedIndex(4);
        setPresentTabVisible(evt,new Color(24,145,143),Color.white);
        this.TYPE_SEARCHING = "RANK";

    }//GEN-LAST:event_RankClick

    private void ShiftClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ShiftClick
        // TODO add your handling code here:

        tpnMain.setSelectedIndex(5);   
        setPresentTabVisible(evt,new Color(24,145,143),Color.white);
        this.TYPE_SEARCHING = "SHIFT";

    }//GEN-LAST:event_ShiftClick

    private void AccountClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AccountClick
        // TODO add your handling code here:
        tpnMain.setSelectedIndex(6);   
        setPresentTabVisible(evt,new Color(24,145,143),Color.white);
    }//GEN-LAST:event_AccountClick

    private void AddNewProductClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddNewProductClick
        // TODO add your handling code here:
        AddProduct addPrdForm = new AddProduct(this);
        addPrdForm.setVisible(true);
        addPrdForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_AddNewProductClick

    private void HomeClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeClick
        // TODO add your handling code here:
        tpnMain.setSelectedIndex(7); 
         setPresentTabVisible(evt,new Color(24,145,143),Color.white);
    }//GEN-LAST:event_HomeClick

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        this.lgin.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void DetailProdFoundClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailProdFoundClick
        // TODO add your handling code here:
        if(idProductSelected != null){
            maSp = idProductSelected;
        }
        DetailProduct dtpd = new DetailProduct(this, this.idProductSelected);
        System.out.println(idProductSelected);
        dtpd.setVisible(true);
        dtpd.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_DetailProdFoundClick

    private void btnViewProductFoundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProductFoundActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewProductFoundActionPerformed

    private void btnDeleteProdFoundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteProdFoundMouseClicked
        // TODO add your handling code here:
        delete();
    }//GEN-LAST:event_btnDeleteProdFoundMouseClicked

    private void lblGoSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGoSearchMouseClicked
        // TODO add your handling code here:
        switch(this.TYPE_SEARCHING) {
            case "PRODUCT":
                searchNameSP();
                break;
            case "STAFF":
                searchNameNV();
                break;
            case "CLIENT":
                clientForm.searchNameKH(txtSearch.getText());
                txtSearch.setText("");
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_lblGoSearchMouseClicked

    private void StaffFoundClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffFoundClick
        // TODO add your handling code here:
        DetailStaff frm = new DetailStaff(this, this.idStaffSelected);
        frm.setVisible(true);
        frm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_StaffFoundClick

    private void setPresentTabVisible(java.awt.event.MouseEvent evt,Color currcolor,Color originColor){
        Component hoveredComponent = evt.getComponent();
        JPanel res = null;
        if (hoveredComponent instanceof JLabel) {
            res = (JPanel) ((JLabel) hoveredComponent).getParent();
        } else if (hoveredComponent instanceof JPanel) {
            res = (JPanel) hoveredComponent;
        }
        JPanel supperParent = (JPanel) res.getParent();
        for (Component c : supperParent.getComponents()) {
            if(c.getBackground().equals(currcolor)) {
                c.setBackground(originColor);
                JPanel cc = (JPanel)c;
                for(Component c2 : cc.getComponents()) {
                    if(c2 instanceof JLabel) {
                        ((JLabel)c2).setForeground(new Color(102,102,102));
                    }
                }
            }
        }
        res.setBackground(currcolor);
        for(Component c : res.getComponents()) {
            if(c instanceof JLabel) {
                        ((JLabel)c).setForeground(Color.white);
                    }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain(new LogIn()).setVisible(true);
            }
        });
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.qlchtl.views.MyControls.MyButton btnAddStaff;
    private com.qlchtl.views.MyControls.MyButton btnDeleteProdFound;
    private com.qlchtl.views.MyControls.MyButton btnDeleteStaffFound;
    private com.qlchtl.views.MyControls.MyButton btnDetailStaffFound;
    private com.qlchtl.views.MyControls.MyButton btnViewProductFound;
    private javax.swing.JLabel iconAccount;
    private javax.swing.JLabel iconClient;
    private javax.swing.JLabel iconInvoice;
    private javax.swing.JLabel iconProduct;
    private javax.swing.JLabel iconRank;
    private javax.swing.JLabel iconShift;
    private javax.swing.JLabel iconStaff;
    private javax.swing.JLabel imgProductFound;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAddNewProd;
    private javax.swing.JLabel lblAvataStaffFound;
    private javax.swing.JLabel lblClient;
    private javax.swing.JLabel lblCodeProductFound;
    private javax.swing.JLabel lblCodeStaffFound;
    private javax.swing.JLabel lblGoSearch;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblInvoice;
    private javax.swing.JLabel lblLogout;
    private javax.swing.JLabel lblNameStaffFound;
    private javax.swing.JLabel lblPhoneStaffFound;
    private javax.swing.JLabel lblPriceProdFound;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProductNameFound;
    private javax.swing.JLabel lblQuantityProductFound;
    private javax.swing.JLabel lblRank;
    private javax.swing.JLabel lblShift;
    private javax.swing.JLabel lblStaff;
    private javax.swing.JLabel lblStateStaffFound;
    private javax.swing.JLabel lblTabName;
    private com.qlchtl.views.MyControls.MyPanel myPanel1;
    private com.qlchtl.views.MyControls.MyPanel myPanel2;
    private com.qlchtl.views.MyControls.MyPanel myPanel3;
    private com.qlchtl.views.MyControls.MyPanelBoxShadow myPanelBoxShadow1;
    private com.qlchtl.views.MyControls.MyPanelBoxShadow myPanelBoxShadow2;
    private com.qlchtl.views.MyControls.MyPanelBoxShadow myPanelBoxShadow3;
    private com.qlchtl.views.MyControls.MyPanelBoxShadow myPanelBoxShadow4;
    private javax.swing.JPanel pnlAccount;
    private com.qlchtl.views.MyControls.MyPanelBoxShadow pnlAddNewPrd;
    private javax.swing.JPanel pnlClient;
    private javax.swing.JPanel pnlHeaderStaff;
    private com.qlchtl.views.MyControls.MyPanelBoxShadow pnlHome;
    private javax.swing.JPanel pnlInvoice;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlProduct;
    private javax.swing.JPanel pnlScrollStaff;
    private javax.swing.JPanel pnlShift;
    private javax.swing.JPanel pnlStaff;
    private javax.swing.JScrollPane scpProduct;
    private javax.swing.JScrollPane scpStaff;
    private javax.swing.JTabbedPane tpnMain;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JPanel ucProduct;
    private javax.swing.JPanel ucStaff;
    // End of variables declaration//GEN-END:variables


    SanPham getFormSanPham() {
        SanPham sp = new SanPham();
        sp.setMaSP(lblCodeProductFound.getText());
        sp.setTrangThai("0");
        return sp;
    }

    void delete() {
        int choice = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xóa nhân viên này?",
                "Xác nhận xóa",
                JOptionPane.OK_CANCEL_OPTION
        );

        if (choice == JOptionPane.OK_OPTION) {
            SanPham sp = getFormSanPham();
            try {
                sanPhamDao.updateTrangThai(sp);
                MsgBox.alert(this, "Xóa thành công!");
                List<SanPham> listsp = sanPhamDao.selectAll();
                renderItemProdWithThread(listsp);
            } catch (Exception e) {
                MsgBox.alert(this, "Xóa thất bại!");
            }
        }
    }



    void searchNameSP(){
        String nameProduct = txtSearch.getText();
        List<SanPham> searchProduct = sanPhamDao.selectByName(nameProduct);
        if(searchProduct.size() > 0){
            renderItemProdWithThread(searchProduct);
        }
        else{
            MsgBox.alert(this, "Không có sản phẩm nào được tìm thấy");
            List<SanPham> listsp = sanPhamDao.selectAll();
            renderItemProdWithThread(listsp);
        }
        txtSearch.setText("");
    }

    void searchNameNV(){
        String nameStaff = txtSearch.getText();
        List<NhanVien> searchStaff = nhanVienDao.selectByName(nameStaff);
        if(searchStaff.size() > 0){
            renderItemStaffWithThread(searchStaff);
        }
        else{
            MsgBox.alert(this, "Không có nhân viên nào được tìm thấy");
            List<NhanVien> searchStaffAll = nhanVienDao.selectAll();
            renderItemStaffWithThread(searchStaffAll);
        }
        txtSearch.setText("");
    }


    NhanVien getFormNhanVien(String ms) {
        NhanVien nv = new NhanVien();
        nv.setMaNV(ms);
        nv.setTrangThai(false);
        System.out.println(ms);
        return nv;
    }
    public void deleteNhanVien(String code) {
        NhanVien sp = getFormNhanVien(code);
        try {
            System.out.println(sp.getMaNV());
            nhanVienDao.updateTrangThai(sp);
            MsgBox.alert(this, "Xóa nhân viên thành công!");
            loadNV();
        } catch (Exception e) {
            MsgBox.alert(this, "Xóa nhân viên thất bại!");
        }
    }



    public void loadSP(){
        List<SanPham> listsp = sanPhamDao.selectAll();
        renderItemProdWithThread(listsp);
    }

    public void loadNV(){
        List<NhanVien> listsp = nhanVienDao.selectAll();
        renderItemStaffWithThread(listsp);
    }

    @Override
    public void onUpdateCompleteSanPham() {
        loadSP();
    }

    @Override
    public void onUpdateCompleteNhanVien() {
        loadNV();
    }
}
