/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.qlchtl.views;

import com.qlchtl.dao.ChiTietHoaDonDao;
import com.qlchtl.dao.HoaDonDao;
import com.qlchtl.dao.KhachHangDao;
import com.qlchtl.dao.KhoDao;
import com.qlchtl.dao.NhanVienDao;
import com.qlchtl.dao.SanPhamDao;
import com.qlchtl.entity.ChiTietHoaDon;
import com.qlchtl.entity.HoaDon;
import com.qlchtl.entity.KhachHang;
import com.qlchtl.entity.Kho;
import com.qlchtl.entity.NhanVien;
import com.qlchtl.entity.SanPham;
import com.qlchtl.print.ReportManager;
import com.qlchtl.print.model.FieldReportPayment;
import com.qlchtl.print.model.ParameterReportPayment;
import com.qlchtl.utils.MsgBox;
import com.qlchtl.views.SubComponent.InvoiceForm;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.JasperCompileManager;
/**
 *
 * @author Dell
 */
public class JFHoaDon extends javax.swing.JFrame {

    /**
     * Creates new form JFHoaDon
     */
    private String MaHD="";
    private String MaNV;
    private String TenNV;
    private String SDTNV;

    InvoiceForm parForm;
    public JFHoaDon(InvoiceForm parForm) {
        initComponents();
        this.parForm = parForm;
        this.lblNowDate.setText(LocalDate.now().toString());
        remakeControls();
        loadCustomers();
        loadProducts();
        createMaHD();
        clearTable();
        loadData();
        updateTongTien();
        setLocationRelativeTo(null);
        getInfoNV();
    }
    private void remakeControls() {
        //table
        jtbInvoice.getTableHeader().setOpaque(false);
        jtbInvoice.getTableHeader().setBackground(new Color(174,0,0));
        jtbInvoice.getTableHeader().setForeground(new Color(0,0,0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myPanel2 = new com.qlchtl.views.MyControls.MyPanel();
        myPanel3 = new com.qlchtl.views.MyControls.MyPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbInvoice = new javax.swing.JTable();
        myPanel4 = new com.qlchtl.views.MyControls.MyPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jcbIDSanPham = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        jtxtQuantity = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jlbPrice = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jbtnSCanSanPham = new com.qlchtl.views.MyControls.MyButton();
        jbtnAddSanPham = new com.qlchtl.views.MyControls.MyButton();
        jlblIDNhanvien = new javax.swing.JLabel();
        jlblTenNhanvien = new javax.swing.JLabel();
        jlblSDTNhanvien = new javax.swing.JLabel();
        jlblTenKhach = new javax.swing.JLabel();
        jlblSDTKhach = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jbtnCreate = new com.qlchtl.views.MyControls.MyButton();
        jcbIDKhachHang = new javax.swing.JComboBox<>();
        jbtnDeleteSanPham = new com.qlchtl.views.MyControls.MyButton();
        myPanel1 = new com.qlchtl.views.MyControls.MyPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblNowDate = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        myPanel2.setBackground(new java.awt.Color(174, 0, 0));

        javax.swing.GroupLayout myPanel2Layout = new javax.swing.GroupLayout(myPanel2);
        myPanel2.setLayout(myPanel2Layout);
        myPanel2Layout.setHorizontalGroup(
            myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        myPanel2Layout.setVerticalGroup(
            myPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        myPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));
        jPanel3.setPreferredSize(new java.awt.Dimension(333, 3));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setPreferredSize(new java.awt.Dimension(347, 3));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel10.setText("Create By");

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 0, 18)); // NOI18N
        jLabel11.setText("Bill To");

        jLabel12.setText("ID:");

        jLabel13.setText("Name:");

        jLabel14.setText("Phone:");

        jLabel15.setText("ID:");

        jLabel16.setText("Name:");

        jLabel17.setText("Phone:");

        jtbInvoice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã sản phẩm", "Giá tiền", "Số lượng", "Thành tiền", "Xóa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbInvoice.setFocusable(false);
        jtbInvoice.setGridColor(new java.awt.Color(174, 0, 0));
        jtbInvoice.setRowHeight(40);
        jtbInvoice.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jtbInvoice.setShowGrid(false);
        jtbInvoice.setShowHorizontalLines(true);
        jtbInvoice.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jtbInvoice);
        jtbInvoice.getAccessibleContext().setAccessibleName("");

        myPanel4.setBackground(new java.awt.Color(174, 0, 0));
        myPanel4.setRoundBottomLeft(10);
        myPanel4.setRoundBottomRight(10);
        myPanel4.setRoundTopLeft(10);
        myPanel4.setRoundTopRight(10);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Product ID:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));

        jcbIDSanPham.setEditable(true);
        jcbIDSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbIDSanPhamActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Quantity:");

        jtxtQuantity.setBackground(new java.awt.Color(174, 0, 0));
        jtxtQuantity.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jtxtQuantity.setForeground(new java.awt.Color(255, 255, 255));
        jtxtQuantity.setText("1");
        jtxtQuantity.setBorder(null);
        jtxtQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtQuantityActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Price:");

        jlbPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jlbPrice.setForeground(new java.awt.Color(255, 255, 255));
        jlbPrice.setText("10.000đ");

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        jbtnSCanSanPham.setBorder(null);
        jbtnSCanSanPham.setForeground(new java.awt.Color(102, 102, 102));
        jbtnSCanSanPham.setText("Scan");
        jbtnSCanSanPham.setBorderColor(new java.awt.Color(255, 255, 255));
        jbtnSCanSanPham.setColor(new java.awt.Color(255, 204, 204));
        jbtnSCanSanPham.setColorClick(new java.awt.Color(255, 153, 204));
        jbtnSCanSanPham.setColorOver(new java.awt.Color(255, 153, 153));
        jbtnSCanSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnSCanSanPham.setRadius(10);
        jbtnSCanSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSCanSanPhamActionPerformed(evt);
            }
        });

        jbtnAddSanPham.setBorder(null);
        jbtnAddSanPham.setForeground(new java.awt.Color(102, 102, 102));
        jbtnAddSanPham.setText("Add");
        jbtnAddSanPham.setBorderColor(new java.awt.Color(255, 255, 255));
        jbtnAddSanPham.setColor(new java.awt.Color(255, 204, 204));
        jbtnAddSanPham.setColorClick(new java.awt.Color(255, 153, 204));
        jbtnAddSanPham.setColorOver(new java.awt.Color(255, 153, 153));
        jbtnAddSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnAddSanPham.setRadius(10);
        jbtnAddSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myPanel4Layout = new javax.swing.GroupLayout(myPanel4);
        myPanel4.setLayout(myPanel4Layout);
        myPanel4Layout.setHorizontalGroup(
            myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel4Layout.createSequentialGroup()
                        .addGroup(myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(57, 57, 57)
                        .addGroup(myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(myPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbIDSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnSCanSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jbtnAddSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        myPanel4Layout.setVerticalGroup(
            myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel4Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jcbIDSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jtxtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jlbPrice))
                .addGap(19, 19, 19)
                .addGroup(myPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSCanSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnAddSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jlblIDNhanvien.setText("NV00000001");

        jlblTenNhanvien.setText("Nguyen Van Tai");

        jlblSDTNhanvien.setText("0928895717");

        jlblTenKhach.setText("Nguyễn Văn A");

        jlblSDTKhach.setText("0123456789");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setText("Stored score:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setText("Used score:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setText("0");

        jTextField1.setText("0");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("Price:");

        jTextField2.setBackground(new java.awt.Color(255, 204, 204));
        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField2.setText("00.0");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jbtnCreate.setBackground(new java.awt.Color(174, 0, 0));
        jbtnCreate.setForeground(new java.awt.Color(255, 255, 255));
        jbtnCreate.setText("Create");
        jbtnCreate.setBorderColor(new java.awt.Color(174, 0, 0));
        jbtnCreate.setColor(new java.awt.Color(174, 0, 0));
        jbtnCreate.setColorClick(new java.awt.Color(255, 51, 51));
        jbtnCreate.setColorOver(new java.awt.Color(153, 0, 0));
        jbtnCreate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbtnCreate.setRadius(20);
        jbtnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCreateActionPerformed(evt);
            }
        });

        jcbIDKhachHang.setEditable(true);
        jcbIDKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbIDKhachHangActionPerformed(evt);
            }
        });

        jbtnDeleteSanPham.setBorder(null);
        jbtnDeleteSanPham.setForeground(new java.awt.Color(102, 102, 102));
        jbtnDeleteSanPham.setText("Delete");
        jbtnDeleteSanPham.setBorderColor(new java.awt.Color(255, 255, 255));
        jbtnDeleteSanPham.setColor(new java.awt.Color(255, 204, 204));
        jbtnDeleteSanPham.setColorClick(new java.awt.Color(255, 153, 204));
        jbtnDeleteSanPham.setColorOver(new java.awt.Color(255, 153, 153));
        jbtnDeleteSanPham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jbtnDeleteSanPham.setRadius(10);
        jbtnDeleteSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteSanPhamActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout myPanel3Layout = new javax.swing.GroupLayout(myPanel3);
        myPanel3.setLayout(myPanel3Layout);
        myPanel3Layout.setHorizontalGroup(
            myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
            .addGroup(myPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(myPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jlblIDNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jlblSDTNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(myPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(jlblTenNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblSDTKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblTenKhach, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbIDKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(88, 88, 88))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                        .addComponent(myPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                        .addComponent(jbtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(myPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(myPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(46, 46, 46)
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                        .addComponent(jbtnDeleteSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        myPanel3Layout.setVerticalGroup(
            myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(myPanel3Layout.createSequentialGroup()
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jlblIDNhanvien))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jlblTenNhanvien, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jlblSDTNhanvien)))
                    .addGroup(myPanel3Layout.createSequentialGroup()
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jcbIDKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jlblTenKhach))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jlblSDTKhach))))
                .addGap(18, 18, 18)
                .addComponent(jbtnDeleteSanPham, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(myPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel3Layout.createSequentialGroup()
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(myPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(15, 15, 15)
                .addComponent(jbtnCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        myPanel1.setBackground(new java.awt.Color(102, 102, 102));
        myPanel1.setRoundBottomLeft(87);
        myPanel1.setRoundBottomRight(87);
        myPanel1.setRoundTopLeft(87);
        myPanel1.setRoundTopRight(87);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGO");

        javax.swing.GroupLayout myPanel1Layout = new javax.swing.GroupLayout(myPanel1);
        myPanel1.setLayout(myPanel1Layout);
        myPanel1Layout.setHorizontalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        myPanel1Layout.setVerticalGroup(
            myPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(myPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("Xirkle k");

        jLabel3.setText("Address:  Ahi hi hi ");

        jLabel4.setText("Phone:  0928895717");

        jLabel5.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 102, 102));
        jLabel5.setText("INVOICE");

        jLabel6.setText("CODE: ");

        jLabel7.setText("12345");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 2));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        jLabel8.setText("DATE:");

        lblNowDate.setText("24/11/2003");

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 118, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(myPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(myPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(myPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(351, 351, 351)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblNowDate, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(myPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNowDate)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4))
                            .addComponent(myPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)))
                .addGap(42, 42, 42)
                .addComponent(myPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jcbIDSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbIDSanPhamActionPerformed
        // TODO add your handling code here:
        updateProductInfo();
    }//GEN-LAST:event_jcbIDSanPhamActionPerformed

    private void jcbIDKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbIDKhachHangActionPerformed
        // TODO add your handling code here:
        updateCustomerInfo();
    }//GEN-LAST:event_jcbIDKhachHangActionPerformed

    private void jbtnAddSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddSanPhamActionPerformed
        // TODO add your handling code here:
        ChiTietHoaDonDao chitiethoadondao=new ChiTietHoaDonDao();
        ChiTietHoaDon chitiethoadon=new ChiTietHoaDon();
        chitiethoadon.setMaSp((String) jcbIDSanPham.getSelectedItem());
        chitiethoadon.setMaHD(MaHD);
        chitiethoadon.setMaCH("CH00000001");
        chitiethoadon.setGiaThanhToan(jlbPrice.getText());
        chitiethoadon.setsL(Integer.parseInt(jtxtQuantity.getText()));
        double tongtien = Double.parseDouble(jlbPrice.getText())*Integer.parseInt(jtxtQuantity.getText());
        DecimalFormat df = new DecimalFormat("0.00");
        chitiethoadon.setTongTien(df.format(tongtien));
        chitiethoadondao.insert(chitiethoadon);
        loadData();
        updateTongTien();
    }//GEN-LAST:event_jbtnAddSanPhamActionPerformed

    private void jbtnDeleteSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteSanPhamActionPerformed
        // TODO add your handling code here:
        int selectedRow=jtbInvoice.getSelectedRow();
        if (selectedRow != -1) {
       
            String MaSP =(String) jtbInvoice.getValueAt(selectedRow, 0);

            ChiTietHoaDonDao chitiethoadondao=new ChiTietHoaDonDao();
            chitiethoadondao.delete(MaSP, MaHD);
            loadData();
            updateTongTien();
        } else {
            MsgBox.alert(this, "Vui lòng chọn hàng để xóa!");
        }
    }//GEN-LAST:event_jbtnDeleteSanPhamActionPerformed

    private void jtxtQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtQuantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtQuantityActionPerformed

    
    private void loadInvoiceReport()  {
       try {
           ReportManager.getInstance().compileReport();
           ParameterReportPayment data = new ParameterReportPayment(this.MaHD, jTextField2.getText(), jTextField1.getText(), jLabel25.getText(), null);
           ReportManager.getInstance().printReportPayment(data);
       }catch(Exception e) {
           e.printStackTrace();
       }
    }
    
    private void jbtnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCreateActionPerformed
        // TODO add your handling code here:
        KhachHangDao khachhangdao=new KhachHangDao();
        KhachHang khachhang=khachhangdao.selectById((String) jcbIDKhachHang.getSelectedItem());
        double giaTri = Double.parseDouble(jTextField2.getText());
        
        double limit = 0.1 * giaTri;
        if(!jTextField1.getText().matches("\\d+")) 
        {
            jTextField1.setText("");
            MsgBox.alert(this, "Điểm sử dụng không hợp lệ!");
        }
        else
        {   int diemSuDung = Integer.parseInt(jTextField1.getText());
             if (diemSuDung > limit) {
                        MsgBox.alert(this, "Số điểm sử dụng không được vượt quá 10% giá trị đơn hàng!");
                }
            else if(khachhang.getSoDiemHienCo()>=Integer.parseInt(jTextField1.getText()))
            {    
                double giaTriMoi = giaTri - diemSuDung;
                HoaDonDao hoadondao=new HoaDonDao();
                HoaDon hoadon=new HoaDon();
                hoadon.setMaHD(MaHD);
                hoadon.setNgayXuat(LocalDate.now());
                hoadon.setGiaTri(String.valueOf(giaTriMoi));
                hoadon.setMaKH((String) jcbIDKhachHang.getSelectedItem());
                hoadon.setMaNV((String) jlblIDNhanvien.getText());
                hoadon.setDiemTich(Integer.parseInt(jLabel25.getText()));
                hoadon.setDiemSuDung(Integer.parseInt(jTextField1.getText()));
                hoadondao.update(hoadon);
                updateSoluong();
                MsgBox.alert(this, "Thanh toán thành công!");
                khachhangdao.updateSuDungDiem(khachhang,Integer.parseInt(jTextField1.getText()) );
                khachhangdao.updateThemDiem(khachhang, Integer.parseInt(jLabel25.getText()));
                loadInvoiceReport();
                hoadonmoi=1;
                createMaHD();
                loadData();
                updateTongTien();
                jTextField1.setText("0");
                parForm.reloadForm();

            }
            else 
                MsgBox.alert(this, "Điểm hiện có không đủ để dùng!");
            }
    }//GEN-LAST:event_jbtnCreateActionPerformed

    private void jbtnSCanSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSCanSanPhamActionPerformed
                               
        // TODO add your handling code here:
        Scan scan;
        scan = new Scan(this);
        scan.setVisible(true);
        scan.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
   
    }//GEN-LAST:event_jbtnSCanSanPhamActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    
    // End of variables declaration                   
    private void updateCustomerInfo() {
        KhachHangDao khachhangdao=new KhachHangDao();
        String selectedCustomerId=(String) jcbIDKhachHang.getSelectedItem();
        KhachHang khachhang=khachhangdao.selectById(selectedCustomerId);
        if(khachhang!=null)
        {
            jlblTenKhach.setText(khachhang.getHoTenKH());
            jlblSDTKhach.setText(khachhang.getsDT());
        }
        else
        {
            MsgBox.alert(this, "Khách hàng không tồn tại!");
        }
    }
    private void loadCustomers() 
    {
        KhachHangDao khachhangdao=new KhachHangDao();
        List<KhachHang> khachhangs= khachhangdao.selectAll();
        for(KhachHang khachhang:khachhangs)
        {
            if(!khachhang.getTrangThai().equals("0")){
                jcbIDKhachHang.addItem(khachhang.getMaKH());
            }
        }
    }
    private void updateSoluong()
    {
        ChiTietHoaDonDao chiTietHoaDonDao=new ChiTietHoaDonDao();
        KhoDao khoDao=new KhoDao();
        List<ChiTietHoaDon> chiTietHoaDons= chiTietHoaDonDao.selectByMaHD(MaHD);
        for(ChiTietHoaDon chiTietHoaDon:chiTietHoaDons)
        {
            Kho kho=khoDao.selectById(chiTietHoaDon.getMaSp());
            if(kho.getSoLuong()>=chiTietHoaDon.getsL())
                kho.setSoLuong(kho.getSoLuong()-chiTietHoaDon.getsL());
            else
                 MsgBox.alert(this, "Số lượng sản phẩm trong kho không đủ!");
        }
    }
    private void loadProducts() 
    {
        SanPhamDao sanphamdao=new SanPhamDao();
        List<SanPham> sanphams= sanphamdao.selectAll();
        for(SanPham sanpham:sanphams)
        {
            if(!sanpham.getTrangThai().equals("0"))
                jcbIDSanPham.addItem(sanpham.getMaSP());
        }
    }
    private void updateProductInfo() {
        SanPhamDao sanphamdao=new SanPhamDao();
        String selectedProductId=(String) jcbIDSanPham.getSelectedItem();
        SanPham sanpham=sanphamdao.selectById(selectedProductId);
        if(sanpham==null||sanpham.getTrangThai().equals("0"))
        {
            MsgBox.alert(this, "Sản phẩm không tồn tại!");
            jcbIDSanPham.setSelectedIndex(0);
            sanpham=sanphamdao.selectById((String)jcbIDSanPham.getSelectedItem());
            jtxtQuantity.setText("1");
        }
        else
        {
            jlbPrice.setText(sanpham.getTienThanhToan());
        }
    }
    //jtbInvoice
    private void loadData()
    {
        ChiTietHoaDonDao chitiethoadondao=new ChiTietHoaDonDao();
         
        List<ChiTietHoaDon> chitiethoadons=chitiethoadondao.selectByMaHD(MaHD);
        DefaultTableModel model = new DefaultTableModel();
         model.addColumn("Mã sản phẩm");
        model.addColumn("Giá tiền");
        model.addColumn("Số lượng");
        model.addColumn("Thành tiền");
        for(ChiTietHoaDon chitiethoadon: chitiethoadons)
        {
            String[] rowdata={
                    chitiethoadon.getMaSp(),
                    chitiethoadon.getGiaThanhToan(),
                    String.valueOf(chitiethoadon.getsL()),
                    chitiethoadon.getTongTien(), 
            };
            model.addRow(rowdata);
        }
        jtbInvoice.setModel(model);
        jLabel7.setText(MaHD);
    }
    private int hoadonmoi=0;
    private void createMaHD()
    {
        String lastInvoiceCode = ""; 
        String nextInvoiceCode = ""; 
        HoaDonDao hoadondao=new HoaDonDao();
        int SoLuongHoaDon=hoadondao.tongHoaDon();
        lastInvoiceCode=String.format("HD%08d",SoLuongHoaDon);
        nextInvoiceCode=String.format("HD%08d",SoLuongHoaDon+hoadonmoi);
        MaHD=nextInvoiceCode;
        HoaDon hoadon= hoadondao.selectById(MaHD);
        if(hoadon==null)
        {
            hoadon =new HoaDon();
            hoadon.setMaHD(MaHD);
            hoadon.setNgayXuat(LocalDate.now());
            hoadon.setGiaTri("10000");
            hoadondao.insert(hoadon);
            hoadonmoi=0;
        }
        
    }
    private void updateTongTien()
    {
        ChiTietHoaDonDao chitiethoadondao= new ChiTietHoaDonDao();
        List<ChiTietHoaDon> chitiethoadons=chitiethoadondao.selectByMaHD(MaHD);
        double Sum=0;
        for(ChiTietHoaDon chitiethoadon:chitiethoadons)
        {
            Sum=Sum+Double.parseDouble(chitiethoadon.getTongTien());
        }
        jTextField2.setText(Double.toString(Sum));
        int diemtich=Double.valueOf(Sum).intValue()/10;
        jLabel25.setText(Integer.toString(diemtich));
    }
    public void getMaSPFromScan(String MaSP)
    {
        jcbIDSanPham.setSelectedItem(MaSP);
        System.out.print(MaSP);
    }
    
    public void setTable(String code) {
        jcbIDSanPham.setSelectedItem(code);
        SanPhamDao sanPhamDao=new SanPhamDao();
        SanPham sanpham=sanPhamDao.selectById(code);
        if((sanpham!=null)&&(sanpham.getTrangThai().equals("1")))
        {
            ChiTietHoaDonDao chitiethoadondao=new ChiTietHoaDonDao();
            ChiTietHoaDon chitiethoadon=new ChiTietHoaDon();
            chitiethoadon.setMaSp((String) jcbIDSanPham.getSelectedItem());
            chitiethoadon.setMaHD(MaHD);
            chitiethoadon.setMaCH("CH00000001");
            chitiethoadon.setGiaThanhToan(jlbPrice.getText());
            chitiethoadon.setsL(Integer.parseInt(jtxtQuantity.getText()));
            double tongtien = Double.parseDouble(jlbPrice.getText())*Integer.parseInt(jtxtQuantity.getText());
            DecimalFormat df = new DecimalFormat("0.00");
            chitiethoadon.setTongTien(df.format(tongtien));
            chitiethoadondao.insert(chitiethoadon);
            loadData();
            updateTongTien();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private com.qlchtl.views.MyControls.MyButton jbtnAddSanPham;
    private com.qlchtl.views.MyControls.MyButton jbtnCreate;
    private com.qlchtl.views.MyControls.MyButton jbtnDeleteSanPham;
    private com.qlchtl.views.MyControls.MyButton jbtnSCanSanPham;
    private javax.swing.JComboBox<String> jcbIDKhachHang;
    public javax.swing.JComboBox<String> jcbIDSanPham;
    private javax.swing.JLabel jlbPrice;
    private javax.swing.JLabel jlblIDNhanvien;
    private javax.swing.JLabel jlblSDTKhach;
    private javax.swing.JLabel jlblSDTNhanvien;
    private javax.swing.JLabel jlblTenKhach;
    private javax.swing.JLabel jlblTenNhanvien;
    private javax.swing.JTable jtbInvoice;
    private javax.swing.JTextField jtxtQuantity;
    private javax.swing.JLabel lblNowDate;
    private com.qlchtl.views.MyControls.MyPanel myPanel1;
    private com.qlchtl.views.MyControls.MyPanel myPanel2;
    private com.qlchtl.views.MyControls.MyPanel myPanel3;
    private com.qlchtl.views.MyControls.MyPanel myPanel4;
    // End of variables declaration//GEN-END:variables
    void getInfoNV()
    {
        MaNV=LogIn.getMaNV();
        System.out.print(MaNV);
        NhanVienDao nhanVienDao =new NhanVienDao();
        NhanVien nhanVien=nhanVienDao.selectById(MaNV);
        TenNV=nhanVien.getHoTenNV();
        SDTNV=nhanVien.getSdt();
        jlblIDNhanvien.setText(MaNV);
        jlblTenNhanvien.setText(TenNV);
        jlblSDTNhanvien.setText(SDTNV);
    }
    private void clearTable(){
        ChiTietHoaDonDao chitiethoadondao=new ChiTietHoaDonDao();
        chitiethoadondao.deleteAll(MaHD);
    }
}
